### ISSUE TITLE
Mention our Scikit-HEP tutorials somewhere on the website

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/scikit-hep.github.io#109]
Indeed the tutorials available as a Jupyter notebook at https://scikit-hep.org/scikit-hep-tutorials are not mentioned anywhere, and they should. (See discussion at https://github.com/scikit-hep/scikit-hep.github.io/issues/108.)

A possible place to mention the tutorials is the https://scikit-hep.org/resources page.

**Comment by eduardo-rodrigues** [comment]
How about we add the link under https://scikit-hep.org/resources, @henryiii? To me that's reasonable.

**Comment by henryiii** [comment]
For now, sure. Maybe once they are filled out a bit, we could make the link more prominent.

**Comment by eduardo-rodrigues** [comment]
Absolutely :-).
