### ISSUE TITLE
Revision of MANIFEST.in section use of prune

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/scikit-hep.github.io#130]
Given https://github.com/scikit-hep/pyhf/pull/1449 and @kratsg's `scikit-build` Issue which motivated the PR, it seems that current use of `prune` in the [`MANIFEST.in` section of the Packaging docs](https://github.com/scikit-hep/scikit-hep.github.io/blob/2f61a73a33890f47876843b5e967d388c936ded5/pages/developers/packaging.md#manifestin-usually-required) 

```
prune *
graft src
graft tests

include LICENSE README.md pyproject.toml setup.py setup.cfg
global-exclude __pycache__ *.py[cod] .*
```

might need to get revised to something like

```
prune **
graft src
graft tests

include LICENSE README.md pyproject.toml setup.py setup.cfg
global-exclude __pycache__ *.py[cod]
```

as `prune *` is not actually removing _all_ files from the manifest to start with.

If we're not missing anything we're happy to make a PR for this, but I thought we'd bring it up for discussion first. 

@henryiii @eduardo-rodrigues let us know if you have any concerns here.

**Comment by eduardo-rodrigues** [comment]
I trust you - do not know the syntax by heart and remember having to try several things 2-3 years ago when playing with MANIFEST files :-).
