### ISSUE TITLE
Can you add an FAQ entry saying what HEP stands for?

### ISSUE THREAD

**Issue by pieper** [scikit-hep/scikit-hep.github.io#187]
Or even better define HEP on the main page.

**Comment by pieper** [comment]
Ah, of course!  It makes sense but I literally had no guess.  I come from the medical imaging community (slicer.org) and was pointed to one of the packages you provide.  Thank you for answering : )

**Comment by eduardo-rodrigues** [comment]
Thank you. Had a look at slicer.org - quite a big thing!

**Comment by pieper** [comment]
Thanks so much for the change - it'll help the ignorant outsiders like me 👍 

> Had a look at slicer.org - quite a big thing!

Yes, it's a beast!
