### ISSUE TITLE
HTTPS for scikit-hep.org

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/scikit-hep.github.io#19]
Can scikit-hep.org have HTTPS support added? It would be nice in general to have this, as this also affects all the project pages as well.

Since this is a custom domain, and not just using scikit-hep.github.io I assume it is [more involved](https://help.github.com/en/github/working-with-github-pages/troubleshooting-custom-domains-and-github-pages#https-errors) then clicking the "Enforce HTTPS" in Settings. Though, I assume that @henryiii knows how to do this, as he has HTTPS working for https://iris-hep.org/.

**Comment by kratsg** [comment]
Done in 0e5b8105612339509161d85a78fbbbd721e18cc8
