### ISSUE TITLE
Add 'name-tests-test' to suggested pre-commit hooks

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/scikit-hep.github.io#227]
As we [advocate for the use of `pytest`](https://scikit-hep.org/developer/pytest), the https://github.com/pre-commit/pre-commit-hooks hook `name-tests-test` might be a useful hook to add to the suggested hooks. Though as

https://github.com/scikit-hep/scikit-hep.github.io/blob/994255a70d69e2e8585d16dc243175335e8a52e7/pages/developers/style.md?plain=1#L24-L41

is about a _minimal_ configuration if the idea here is to add hooks that are agnostic to most other choices then I could make a PR to https://github.com/scikit-hep/cookie instead (if people think this is a good idea in either place I'll happily make a PR to wherever).

**Comment by henryiii** [comment]
At this point adding something is a PR here, in cookie, and in repo-review. :)

**Comment by matthewfeickert** [comment]
> Maybe it would be better as a mention (+ cookie)?

Yeah my plan was to make a PR to cookie (and now repo-review) as well if you thought it was a good idea here.

> Though this is really not meant to be minimal, so I think I'd be okay with it in the standard set.

:+1:
