### ISSUE TITLE
Minor organisation of site menu

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/scikit-hep.github.io#259]
At the moment the "User information" menu contains "Installing conda" and "Resources". I would argue that "Installing conda" is for the "Developers information" (not spefic to Scikit-HEP in particular) and would move the "Getting in touch" presently under menu "About" to menu "User information", which seems more natural.

Thoughts?

**Comment by henryiii** [comment]
The "user" menu is for people wanting to use Scikit-HEP. Developers should generally not be installing conda; building packages in conda is not recommended; conda is for binary distribution only. So the installing conda is very much a "user" item in that sense. I could see "getting in touch" moving under user information, though.

**Comment by eduardo-rodrigues** [comment]
Fair enough concerning the conda page.

I will leave it until early next week for the move of "Getting in touch" since it seems like a no-brainer.
