### ISSUE TITLE
Add Plausible statistics-counter to all HTML pages

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/scikit-hep.github.io#278]
Stefan gave us a `data-domain` for scikit-hep.org; this snippet should be added to every HTML page:

```html
<script defer data-domain="scikit-hep.org" src="https://views.scientific-python.org/js/plausible.js"></script>
```

It doesn't matter where on the page it appears (see a long conversation I had with myself here: https://github.com/scikit-hep/awkward/issues/1819), and I think the `defer` could be replaced by `async`. You just need to find a template that gets rendered on every page you care about. (In my long conversation, I decided that I didn't care about redirects, but that's up to you.) There are templates in [_includes](https://github.com/scikit-hep/scikit-hep.github.io/tree/main/_includes) and [_layouts](https://github.com/scikit-hep/scikit-hep.github.io/tree/main/_layouts).

--------------

By the way—context for anyone seeing this without background—this is a follow-up of a discussion we had on the Scikit-HEP administrators list. The scientific-python.org organization is providing website statistics through Plausible, which we can use on our documentation sites. The reason we want it is to get a sense of what our users are interested in. In particular, the Awkward Array library is organized as a collection of `ak.*` functions, each with its own page; if we find 100× more website traffic to `ak.this` than `ak.that`, then we'll know that `ak.this` is more important (should get more developer attention) than `ak.that`. The usefulness to the scikit-hep.org pages is different: "Are users looking at 'Project News'? 'Packages'? 'User Information'? ...)

In the presentations at SciPy, they said that Plausible is less intrusive than Google Analytics (which I've used in the past). In particular, Google Analytics violates some regulations in Europe, but Plausible does not. So the choices seem to be well thought-through.

**Comment by jpivarski** [comment]
**:bump:** I highly recommend this, because if you want the data later, you'll have to have set it up earlier.

Here's what the output looks like for Awkward Array's documentation:

<img src="https://user-images.githubusercontent.com/1852447/232860766-18ddbe14-841e-4154-be05-c97f59623a3c.png" width="100%">

We learn, for instance, that there's a strong weekday/weekend effect—people who are working—that the documentation is being read primarily in the United States (odd... is there a U.S./Europe split on Awkward Array? something to look into...), that most users are accessing it with Windows—also a surprise, since most of the physicists I know have Macs—that they get to the documentation by direct searches (good; it's intentional), an [average bounce rate](https://web.archive.org/web/20210801014142/https://www.gorocketfuel.com/the-rocket-blog/whats-the-average-bounce-rate-in-google-analytics/), and that most people are going into the User Guide, not the Reference, which is much more complete. At the very least, we'll perhaps need to fill our our blank User Guide pages with pointers to the Reference, since that's where people are looking.

**Comment by eduardo-rodrigues** [comment]
Thanks Jim. Very interesting! I was going to make the comment that Europe is indeed the sum of several. Overall the difference Europo-US is not that large. But I was expecting quite more hits from Switzerland for people posted at CERN; that's unexpected.
Another curiosity is the large number of visitors from the UK and the even reasonably larger number from Germany. Would the latter be thanks to Belle II colleagues?

I have no idea why Windows is so prominent. Is it because several colleagues have Windows laptops or rather desktops in the office. I do but know I am a clear minority around me.

A couple of questions:
1. You need some special account to access these summaries, I guess? Something others here can do as well? The exercise would be particularly interesting for packages with large visibility such as iminuit (@HDembinski) or pyhf (@matthewfeickert)
2. You say above that there are templates on the website but I did not see them. Can you point to an example from the site or Ackward Array's? Are you in fact going to add such stats-counters to the org site, by chance?

**Comment by jpivarski** [comment]
@eduardo-rodrigues and @HDembinski, you need to be able to access [https://views.scientific-python.org/](https://views.scientific-python.org/), and you might need to contact Stéfan van der Walt ([webpage](https://bids.berkeley.edu/people/st%C3%A9fan-van-der-walt), [GitHub](https://github.com/stefanv), Discord: stefanv#0829) for that. I had this conversation with him (last year) on Discord.

We don't need any additional help (beyond accessing the dashboard) for the generic Scikit-HEP pages; we just need to get this text into the HTML of all the pages:

```html
<script defer data-domain="scikit-hep.org" src="https://views.scientific-python.org/js/plausible.js"></script>
```

The `scikit-hep.org` data domain has already been created in Plausible and is waiting for data. The easiest way to get it on all of the Scikit-HEP pages is to add it to one of the templates, but which one depends on how this Jekyll site works. Maybe [_layouts/page.html](https://github.com/scikit-hep/scikit-hep.github.io/blob/main/_layouts/page.html)? Maybe [_includes/head.html](https://github.com/scikit-hep/scikit-hep.github.io/blob/main/_includes/head.html) and [_includes/head_custom.html](https://github.com/scikit-hep/scikit-hep.github.io/blob/main/_includes/head_custom.html)?

Since iminuit has a large community apart from Scikit-HEP (not disjoint, but another large cluster), I think you'll want a specialized `iminuit` (`iminuit.readthedocs.io`?) data domain, since each of these data domains is a separate bucket for aggregating statistics and I think you'll want to see iminuit statistics separately from Scikit-HEP statistics (just as we do for Awkward). That would be another thing to ask Stéfan.

**Comment by HDembinski** [comment]
> The scikit-hep.org data domain has already been created in Plausible and is waiting for data. The easiest way to get it on all of the Scikit-HEP pages is to add it to one of the templates, but which one depends on how this Jekyll site works. Maybe [_layouts/page.html](https://github.com/scikit-hep/scikit-hep.github.io/blob/main/_layouts/page.html)? Maybe [_includes/head.html](https://github.com/scikit-hep/scikit-hep.github.io/blob/main/_includes/head.html) and [_includes/head_custom.html](https://github.com/scikit-hep/scikit-hep.github.io/blob/main/_includes/head_custom.html)?

@jpivarski I assume this is related to the scikit-hep.org website. Do you also know how I can inject this into the sphinx-generated documentation? I was browsing https://www.sphinx-doc.org/en/master/usage/configuration.html and I could not find an option to customize the website head.

In Markdown, it is possible inject arbitrary html code into the markdown code, but Imy docs are written in RST and I don't know how to do that in RST.

**Comment by jpivarski** [comment]
It looks like you could use this Sphinx extension: [sphinx-plausible](https://pypi.org/project/sphinx-plausible/).

I also looked up "Google Analytics in Sphinx" and found [this](https://ericholscher.com/blog/2009/apr/5/adding-google-analytics-sphinx-docs/), since it's a matter of adding a `<script>` tag in either case.

I don't know that it needs to be in the `<head>`. In Awkward Array's documentation, it is in the `<head>`, but the Javascript would run if it were in the `<body>` as well; it would just start later (which might even be preferable, from a page load speed perspective).

**Comment by matthewfeickert** [comment]
@jpivarski while I'm going to try to use [sphinx-plausible](https://pypi.org/project/sphinx-plausible/) can you link to the PR that you used for Awkward?

**Comment by matthewfeickert** [comment]
> It doesn't matter where on the page it appears (see a long conversation I had with myself here: [scikit-hep/awkward#1819](https://github.com/scikit-hep/awkward/issues/1819)), and I think the `defer` could be replaced by `async`

Woops never mind.

**Comment by matthewfeickert** [comment]
pyhf is now reporting at: https://views.scientific-python.org/pyhf.readthedocs.io/
