### ISSUE TITLE
Restructure grouping slightly 

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/scikit-hep.github.io#29]
The current grouping leaves quite a few packages as single items in a group. Here's my suggested changes:

Put *Simulation* into *Interface to HEP libraries*, which would have pyhepmc, numpythia, and pyjet.

Rename *Units and Constants* to *Math* or *Basics* (or something like that), so Vector can be added there later.

Event Processing is a little odd with only one item in it, but I think that's okay. Will eventually have Awkward 1 and 0.

**Comment by eduardo-rodrigues** [comment]
- I agree with the suggestion to merge *Simulation* into *Interface to HEP libraries*.
- OK also to leave "Event processing" as is.
- I would in fact keep *Units and Constants* as is because it really is well-defined.
- For math business, how about we change *Statistics* to *Maths and statistics*? Then the `vector` package would go here. Math and stats are indeed closer together than units.

Let me know how you feel about these modifications, @henryiii.

**Comment by henryiii** [comment]
Will *Units and Constants* ever have more than one package, then?

Both hepunits and vector are "basic" packages that can be used as a foundation for the other packages and have a simple, well-defined purpose. You might argue that Awkward could be in that category, as well. Statistics are things like pyhf, which are large systems for doing statistics and plots. In thinking of what a user would want to see, hepunits and vector seems much more similar than pyhf and vector.

**Comment by eduardo-rodrigues** [comment]
Indeed it is hard to believe that units and constants will ever contain more than one package. OK, fair enough about similarities. I just want to make sure that people find the units and constants package easily. We can try having the package `hepunits` in a *Maths* section, then.

**Comment by henryiii** [comment]
What about having a "Basics", or "Core" section? We could put it at the top, and have the core packages in it (hepunits, vector, and awkward). If we keep this as the "Mathematics" section, then hepgeometry would go in it eventually, while that might/might not be aimed for the Basics/Core section.

**Comment by eduardo-rodrigues** [comment]
I got confused. You mean having units, awkward and vector (eventually) in a *Basics* section? OK, go with that. (I prefer *Basics* compared to *Core* in this instance because some of the other packages are very much "core building blocks", and better not confuse people).
