### ISSUE TITLE
Scikit-HEP badge for project READMEs

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/scikit-hep.github.io#36]
As first [brought up in the Scikit-HEP Gitter](https://gitter.im/Scikit-HEP/community?at=5e1f4a3c84894f56b6655f83) it would be nice if we designed a Scikit-HEP badge that would link to the [project webpage](https://scikit-hep.org/) that all projects would have in their `READMEs`. As the `README`s end up getting put up on PyPI during publishing it could be a useful way to get a curious user from PyPI to the project quickly. So maybe something along the lines of

[![Scikit-HEP](https://img.shields.io/badge/Project-Scikit--HEP-blue)](https://scikit-hep.org/)

but something more interesting.

As @henryiii did a great job with the color pallet choices for the PyPI badges

[![PyPI](https://img.shields.io/pypi/v/boost-histogram?color=blue&logo=PyPI&logoColor=white)](https://pypi.org/project/boost-histogram/)

I'm hoping that he has some thoughts on the badge design as well. :slightly_smiling_face:

**Comment by mayou36** [comment]
While a badge is surely a good way to go, there have been discussions on putting up the logo in a consistent manner (including one for affiliated packages). The advantage of a logo seems to be the easy recognizability of it.

But it does not have to be exclusive in principle. Do you prefer a badge over a logo or rather both?

**Comment by matthewfeickert** [comment]
> Do you prefer a badge over a logo or rather both?

I think definitely a badge but I have no preference on it also a logo or not. A badge is small and easy to get it to work with the current layout of any README (just throw it anywhere with the rest of your badges).

> putting up the logo in a consistent manner (including one for affiliated packages)

A logo is nice, but I think it is harder as that would require all of the Scikit-HEP projects and affiliated projects to have essentially the exact same `README` layout (at least at the top I think) and have logos that are the same size if the goal is to have them in the same place would require a lot of changes to everyone's `README`s. To be clear, I'm not against it, I just think that it requires work from everyone, while a badge requires essentially no effort.

**Comment by henryiii** [comment]
Here's what I'm thinking:

[![Scikit-HEP][sk-badge-aff]](https://scikit-hep.org/)

[![Scikit-HEP][sk-badge]](https://scikit-hep.org/)

[sk-badge-aff]: https://img.shields.io/badge/Scikit--HEP-Affiliated-blue?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAcCAQAAADVGmdYAAADQklEQVQ4y5WUYWjUdRjHv9tutpomSVKL1l646ZpYQmlB85XEyBIUBF9YKBFTi/WiBdPmlISg5iUksQRJcCurQVGNgrI6kLW2+31//9s5rra1bim7nd5x7ZzczN3f/7cX521O16jvy+f3fHh+z/N8fz/gNpn1bOTbPGg2BUqwkGwl+wGAT9AyydOm1X7IQcZt/QIQfzRvAXw2NBk/Jb869KU+0P7Yy4yakyqYFzHreSlQEnvqr2ualiTP87KSJHl/nh/nwfnrHKNfr3quJ3Wl3hu44rTZ+n7/4EQqpAvSlJuona+SufqNNOWmtkcWM2HrctGeZQyHmrXfu+5m9ORtUDwjZb9zJgBu4S8AYDfwBItZy4udRePNblYJVcxBVCe5PaG1jAF2F7sAILKYA3YrwDRXsHp4QtOiigDAPmJ3QYU657pDz3Aps91L+lZywnkAAOwZ8wLABKtDVUxqn6SdANcwYXZD26SLA2wATI95ETCtHGGL/YTRc/dwBTORReZphlWiC4rahxlnEwB9qqv99fZnwG5mjGUqNNvscR5mGWDbeQIwreZ9QG9IvyW5L9dRWt+GSxkzmwAe42BwXa7TcCnbOOos717CVHAdkHxOSp3Jj0E6DNgdHAuWq4CNTNPhx+Zrpvl974MAT/ELoG8lY9602mehvQBAP4eCq4Heu7mFjWY31wABH9s4wntDVYyZZkX1wyy0BwBUwCZO2qOszl/PbmeEfcH7Q1Uc4wFAI/ppFnozvzGnxnRwkpcY5jCv0eFLnUW2kmNsAQBNqSMPXdFXN6864AuutXV2Q25bTgVH7SEA0Kpc9znoc2V0J9CzLFx6q72cCo7ad27kvS7NOFA7JL0C8ABDvffN8f5DjJrWG1nF+l1jKsxDPg0prqWdRfY4o7byZoRHZvzZkB9YPrBVUpcKATYx7jwKAMFy/kH/TMbjmlJExXN9flTSSS0C2MAUa4PlHOG7M6ePaVxprbqlYfl0WtJZ1QD2eV7meL6KfNqrjC5r4zxvVwU6pKyyatfm/hZOAoCq9Jp+lTSs1f/6I6lGXbouSa6n8/pbkpRUo+7AwlKZ9rgfpT116zMd0Ub58N8UKKF4F/6vmHWWL3T+D7YCRP6MAwdKAAAAAElFTkSuQmCC

[sk-badge]: https://img.shields.io/badge/Scikit--HEP-Core-blue?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAcCAQAAADVGmdYAAADQklEQVQ4y5WUYWjUdRjHv9tutpomSVKL1l646ZpYQmlB85XEyBIUBF9YKBFTi/WiBdPmlISg5iUksQRJcCurQVGNgrI6kLW2+31//9s5rra1bim7nd5x7ZzczN3f/7cX521O16jvy+f3fHh+z/N8fz/gNpn1bOTbPGg2BUqwkGwl+wGAT9AyydOm1X7IQcZt/QIQfzRvAXw2NBk/Jb869KU+0P7Yy4yakyqYFzHreSlQEnvqr2ualiTP87KSJHl/nh/nwfnrHKNfr3quJ3Wl3hu44rTZ+n7/4EQqpAvSlJuona+SufqNNOWmtkcWM2HrctGeZQyHmrXfu+5m9ORtUDwjZb9zJgBu4S8AYDfwBItZy4udRePNblYJVcxBVCe5PaG1jAF2F7sAILKYA3YrwDRXsHp4QtOiigDAPmJ3QYU657pDz3Aps91L+lZywnkAAOwZ8wLABKtDVUxqn6SdANcwYXZD26SLA2wATI95ETCtHGGL/YTRc/dwBTORReZphlWiC4rahxlnEwB9qqv99fZnwG5mjGUqNNvscR5mGWDbeQIwreZ9QG9IvyW5L9dRWt+GSxkzmwAe42BwXa7TcCnbOOos717CVHAdkHxOSp3Jj0E6DNgdHAuWq4CNTNPhx+Zrpvl974MAT/ELoG8lY9602mehvQBAP4eCq4Heu7mFjWY31wABH9s4wntDVYyZZkX1wyy0BwBUwCZO2qOszl/PbmeEfcH7Q1Uc4wFAI/ppFnozvzGnxnRwkpcY5jCv0eFLnUW2kmNsAQBNqSMPXdFXN6864AuutXV2Q25bTgVH7SEA0Kpc9znoc2V0J9CzLFx6q72cCo7ad27kvS7NOFA7JL0C8ABDvffN8f5DjJrWG1nF+l1jKsxDPg0prqWdRfY4o7byZoRHZvzZkB9YPrBVUpcKATYx7jwKAMFy/kH/TMbjmlJExXN9flTSSS0C2MAUa4PlHOG7M6ePaVxprbqlYfl0WtJZ1QD2eV7meL6KfNqrjC5r4zxvVwU6pKyyatfm/hZOAoCq9Jp+lTSs1f/6I6lGXbouSa6n8/pbkpRUo+7AwlKZ9rgfpT116zMd0Ub58N8UKKF4F/6vmHWWL3T+D7YCRP6MAwdKAAAAAElFTkSuQmCC

**Comment by eduardo-rodrigues** [comment]
A Scikit-HEP logo we already have, see the website. But I think that for a README a badge is the way to go.e

**Comment by eduardo-rodrigues** [comment]
@henryiii, for your affiliated badge I assume one would have a link to https://scikit-hep.org/affiliated for the badge to make sense? As for the "core" package badge one would like to the main page?

BTW, maybe "Scikit-HEP | Package" is better than "Scikit-HEP | Core" as the latter would mean that other project packages are not core, and that's not the message to bring across.

Otherwise I like it.

**Comment by henryiii** [comment]
Updated. I would have it point to the main page, as the idea is to use it to see the other packages, affiliated or not (and that's where all of them are listed). You don't really care what the other affiliated packages are, you care about what the other packages (including affiliated ones) are.

**Comment by henryiii** [comment]
(No package would ever have both badges, so a link to the main page is always the most useful for the only link, IMO)

**Comment by eduardo-rodrigues** [comment]
I take your point. I was forgetting that the main page now contains all packages; it was not the case before.

**Comment by mayou36** [comment]
> A Scikit-HEP logo we already have, see the website. But I think that for a README a badge is the way to go.e

Yes, sure, I was rather thinking of putting them systematically and with a link into the READMEs.
But I agree with the badge idea, @henryiii what exactly is that thing on the left of the badge? I like it but it also irritates me in the same moment not knowing what it exactly is.

**Comment by henryiii** [comment]
@mayou36 It is a very small, simplified version of the Scikit-HEP logo. Slightly more recognizable on a high-res screen.

**Comment by kratsg** [comment]
i'm not a big fan of saying package (framework, tools, etc...) get classified differently. `Project` or `Supported` or something along those lines sounds better.

**Comment by eduardo-rodrigues** [comment]
Let's try and get to the bottom of this, since everyone likes the idea in the first instance.

So "Scikit-HEP | Affiliated" is clear, from the comments of everyone. As for the actual project packages I see no other adequate choices than (1) "Scikit-HEP | Package" or (2) "Scikit-HEP | Project".

I have no strong feeling for either (1) or (2), though I see the argument for (2) - the badge in a README will basically say that the package is part of the Scikit-HEP project.
@kratsg votes for 2, right?

What about the others who replied? Let's get the badges on the READMEs :-).

**Comment by henryiii** [comment]
We need at least 1-2 affiliated packages to be okay with the badge (@mayou36?). For our packages, I like (1), as all of them are "packages", but Scikit-HEP is the project (though if you consider that the badge links to the project, I'm not against (2) either - I just view the badge as labeling this as a Scikit-HEP package rather than just pointing at the Scikit-HEP project.

I didn't mean that "Package" should change, I just was providing alternative ideas - each one could be labeled by the category they are listed in Scikit-HEP, for example.

PS: Should I simplify the logo by removing the spiral, and just have a Y inside an O? I thought the spiral was a distinctive element of the Scikit-HEP logo, but it doesn't show up well unless you are on a high res screen.

**Comment by eduardo-rodrigues** [comment]
Indeed, I too have a bit of a preference for "Package".

True that the logo in the badge is not so easy to see in standard views, but it does not harm. Fine as is for me.

**Comment by matthewfeickert** [comment]
> I didn't mean that "Package" should change, I just was providing alternative ideas - each one could be labeled by the category they are listed in Scikit-HEP, for example.

> Indeed, I too have a bit of a preference for "Package".

I think I share @kratsg's view on project v. package, but as it seems there is larger leaning towards "Package" then I'd say let's just go with it and get things up. :+1: 

> PS: Should I simplify the logo by removing the spiral, and just have a Y inside an O? I thought the spiral was a distinctive element of the Scikit-HEP logo, but it doesn't show up well unless you are on a high res screen.

Yeah, even on my highest resolution screen I don't think I would be able to identify it had I not known apriori what I was looking at. @henryiii would you be willing to demo this simplified badge design here?

**Comment by mayou36** [comment]
I agree fully on the "affiliated", for packages vs project I tend to "project".

**Comment by eduardo-rodrigues** [comment]
Hi all, seems we're good and there is a slight preference for "project" versus "package" - democracy tells us 3 vs 2 votes.

**Comment by henryiii** [comment]
I'll try an example of the logo without the spiral soon.

**Comment by henryiii** [comment]
[![Scikit-HEP][sk-badge-aff]](https://scikit-hep.org/)

[![Scikit-HEP][sk-badge]](https://scikit-hep.org/)

[sk-badge-aff]: https://img.shields.io/badge/Scikit--HEP-Affiliated-blue?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAcCAYAAAB/E6/TAAAACXBIWXMAAAEZAAABGQHyCY1sAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAA6dJREFUSImdlktonFUUx/930kQ0nYo2JX5NUqSghSq2oIgvcCFaC0EEH2AXUh9FEV1UUaGIC924qY8igo+FQi26sWp8gDS24qOgCOIiKCVomLlnZpxk7Dh2GjMz389F7tgv4zfNJGdzh/M/5/zuud/ch9MKDFgnaUjSnHOu2kuOmb0h6brMMoVHgceBY8ApSVVJ05JOAnXga+BJ4OK0fO/9PZL2AL91AwwBLwLz9GYLwKvAcLtGLpcbMbM5MyuXy+UoDXI14BNFcsABYBy4DLgojDvDZH5PxJaAG4CM937SzCgUCnemQcaB0yFpDngMGFhmefuBh4E/Qt4/tVrtoJlhZq+nJWwHaiH4F2DL2QAp+SPA9wBxHDM7O5svl8vZzqBzgOkAOQGsXwmkbbVabUOj0Wh/1xIw+J+Yy+UuBJ4O4jywdTUQSSoUCgdKpRJxHC+Ees8mxVKr1WoGYf9qId77m80sNrNvgedDvb+A8yQpMzg4OJHJZPoAVavVQ6uBmNmQc+4dSfVWq7Vb0n5JC5KyknZIUiabzdYlqdFoqF6vTxSLxctXwXpNUuSce3RsbOyEc+6kpKNBG5ekjKRLguMTSUNxHE/m8/ntvRK89w9IukvS4SiK3k5Ix8N4aRu0UZIGBgaOAHdIWpfJZI56769fDlIqlTY7515yzlkcx3s65xDGjW1Qf3A0R0ZGJpxzOyX1Oee+MLMd3SDAmjiOD0paK+nB0dHRuY6QhTD2t0EWHJEkRVF0zDl3k6TTkj5OPUIkmdkzwLWSXomi6POUkNFkZxlJM8GxrR0RRdEPzrkbnXOzwHve+/s7IFc55/ZJmmq1Wvu6NH1FGGfaS3B3YrMuOTJKpdJmM5sO+2OvJBWLxUEz+9XM5vP5/DalWDhpqqHu7rYzmzhI96Ys0aZQmEKh8IKZvRV+P9GlEwEPhXoNYCgpvByE2SXCmc6GzeyncCLjvZ8EUi9N4HygEOq92SmuB/4M4pdAf2eBmZmZC7z3lQDb1AXSB3wW6vwNpF54twOtEPQBsLYzplgsfmhmpHUDnAscCvkxsCttMu3gpzhjPwNLNq2ZHU4DsXgr/5jIfa4rJJF0H0vfCp8C9wLDSRCwAdgFfBQ6gMW3wyPLQhKwK4Gv+L81m80mwKkU7Tvgmp4hHcBbgXcTf5ROqwLvA7cBblWQDmA/sLVSqXxTqVQAbmHxJXTWh0vS1vQS5JxrSJoys3JwHXHOxSuZbE+ghE1J2rJSiCT9CxJT5EBIY81lAAAAAElFTkSuQmCC

[sk-badge]: https://img.shields.io/badge/Scikit--HEP-Project-blue?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAcCAYAAAB/E6/TAAAACXBIWXMAAAEZAAABGQHyCY1sAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAA6dJREFUSImdlktonFUUx/930kQ0nYo2JX5NUqSghSq2oIgvcCFaC0EEH2AXUh9FEV1UUaGIC924qY8igo+FQi26sWp8gDS24qOgCOIiKCVomLlnZpxk7Dh2GjMz389F7tgv4zfNJGdzh/M/5/zuud/ch9MKDFgnaUjSnHOu2kuOmb0h6brMMoVHgceBY8ApSVVJ05JOAnXga+BJ4OK0fO/9PZL2AL91AwwBLwLz9GYLwKvAcLtGLpcbMbM5MyuXy+UoDXI14BNFcsABYBy4DLgojDvDZH5PxJaAG4CM937SzCgUCnemQcaB0yFpDngMGFhmefuBh4E/Qt4/tVrtoJlhZq+nJWwHaiH4F2DL2QAp+SPA9wBxHDM7O5svl8vZzqBzgOkAOQGsXwmkbbVabUOj0Wh/1xIw+J+Yy+UuBJ4O4jywdTUQSSoUCgdKpRJxHC+Ees8mxVKr1WoGYf9qId77m80sNrNvgedDvb+A8yQpMzg4OJHJZPoAVavVQ6uBmNmQc+4dSfVWq7Vb0n5JC5KyknZIUiabzdYlqdFoqF6vTxSLxctXwXpNUuSce3RsbOyEc+6kpKNBG5ekjKRLguMTSUNxHE/m8/ntvRK89w9IukvS4SiK3k5Ix8N4aRu0UZIGBgaOAHdIWpfJZI56769fDlIqlTY7515yzlkcx3s65xDGjW1Qf3A0R0ZGJpxzOyX1Oee+MLMd3SDAmjiOD0paK+nB0dHRuY6QhTD2t0EWHJEkRVF0zDl3k6TTkj5OPUIkmdkzwLWSXomi6POUkNFkZxlJM8GxrR0RRdEPzrkbnXOzwHve+/s7IFc55/ZJmmq1Wvu6NH1FGGfaS3B3YrMuOTJKpdJmM5sO+2OvJBWLxUEz+9XM5vP5/DalWDhpqqHu7rYzmzhI96Ys0aZQmEKh8IKZvRV+P9GlEwEPhXoNYCgpvByE2SXCmc6GzeyncCLjvZ8EUi9N4HygEOq92SmuB/4M4pdAf2eBmZmZC7z3lQDb1AXSB3wW6vwNpF54twOtEPQBsLYzplgsfmhmpHUDnAscCvkxsCttMu3gpzhjPwNLNq2ZHU4DsXgr/5jIfa4rJJF0H0vfCp8C9wLDSRCwAdgFfBQ6gMW3wyPLQhKwK4Gv+L81m80mwKkU7Tvgmp4hHcBbgXcTf5ROqwLvA7cBblWQDmA/sLVSqXxTqVQAbmHxJXTWh0vS1vQS5JxrSJoys3JwHXHOxSuZbE+ghE1J2rJSiCT9CxJT5EBIY81lAAAAAElFTkSuQmCC

**Comment by matthewfeickert** [comment]
Yay! These get my vote @henryiii &mdash; thank you so much for taking the time to make them.

Everyone in favor of adopting these, closing the Issue, and getting these adopted in READMEs right away?

**Comment by eduardo-rodrigues** [comment]
I like it.

**Comment by henryiii** [comment]
These need to be added to the scikit-hep pages somewhere so projects and affiliated packages can copy them from a standard source.

**Comment by eduardo-rodrigues** [comment]
Something like https://scikit-hep.org/badges/ I guess?

**Comment by henryiii** [comment]
I was going to add it to a page called "developer information", assuming we could have other tips there later.

**Comment by eduardo-rodrigues** [comment]
Sounds good.

**Comment by henryiii** [comment]
Page is live.

By the way, @jpivarski strips the badges from the PyPI page, so this won't help Uproot. And Jim, I just clicked on the PyPI badge to hop over to PyPI from the Uproot GitHub page. The link therefore was useful to have! ;)

**Comment by henryiii** [comment]
Page is here: https://scikit-hep.org/developer
