### ISSUE TITLE
Citation page

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/scikit-hep.github.io#43]
A page like this might be useful:

https://www.scipy.org/citing.html

**Comment by eduardo-rodrigues** [comment]
Yes, especially true one we start getting paper/proceedings on the project and/or the packages.

I also like the scikit-learn style of having a "how to cite" on the About page, see idea of the latter at https://github.com/scikit-hep/scikit-hep.github.io/issues/41.

**Comment by eduardo-rodrigues** [comment]
The SciPy page now moved to https://scipy.org/citing-scipy/. Will you be working on this anytime soon? Otherwise I can give it a go. CC'ing @HDembinski whom I seem to remember had some points on citation for iminuit, etc.

**Comment by eduardo-rodrigues** [comment]
Unless I hear otherwise I reckonI will add a page citing under the subsection https://scikit-hep.org/about.

**Comment by HDembinski** [comment]
Perhaps better make it a top-level item? We want to make it as easy as possible to do the right thing. If it is under about, you need to click on "About" to see it.

**Comment by eduardo-rodrigues** [comment]
Oops, committed a page just a few second before your comment! But no worries, let's converge on the page content and I can easily move the page to the top level in this MR. Thanks.
