### ISSUE TITLE
[addition] Add ATLAS and IRIS-HEP to user of Scikit-HEP

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/scikit-hep.github.io#90]
`pyhf` is used in multiple analyses in ATLAS, and `uproot` is used all over the place and many projects are used in work for IRIS-HEP. It would be good to add both of these collaborations to the [Who uses Scikit-HEP? page](https://scikit-hep.org/projusers).

**Comment by eduardo-rodrigues** [comment]
Hi @matthewfeickert, totally agree. Amazingly enough I thought about the same thing (for pyhf usage in ATLAS, only) just today!

For what's on that page I always got the email permission from the collaboration's computing and/or software coordinator. If you let me know in private the relevant contacts for ATLAS I'm happy to get in touch as I did so far.

Feel free to list here the list of other experiments and groups/... we should be contacting.

Thanks.

**Comment by matthewfeickert** [comment]
> For what's on that page I always got the email permission from the collaboration's computing and/or software coordinator. If you let me know in private the relevant contacts for ATLAS I'm happy to get in touch as I did so far.

Good idea. I'll send those along later today.

**Comment by eduardo-rodrigues** [comment]
Hi @matthewfeickert, don't forget to send me the information, OK? As for IRIS-HEP, are you in touch with anyone for a permission to publish online?

**Comment by matthewfeickert** [comment]
> don't forget to send me the information, OK?

Thanks for the reminder @eduardo-rodrigues. Currently the ATLAS Software coordinators are Ed Moyse and Johannes Elmsheuser. I'll send you their emails now.

> As for IRIS-HEP, are you in touch with anyone for a permission to publish online?

I think it would be safe to say that both @henryiii and I have permissions to do this and IRIS-HEP wants to be seen as having connections to Scikit-HEP, but to publicly get IRIS-HEP Executive Board approval I'll tag the people who I think will respond first: @pelmer, @bbockelm, @gordonwatts, @davidlange6 (:wave:)

**Comment by eduardo-rodrigues** [comment]
Thanks a lot @matthewfeickert.

IRIS-HEP does have very strong connections. In fact it's the organisation most committed to it 👍 . It develops many of the packages and depends on some for other projects. All great.

**Comment by gordonwatts** [comment]
Obviously, this is totally ok.

**Comment by eduardo-rodrigues** [comment]
Many thanks @gordonwatts. It is really appreciated.

**Comment by bbockelm** [comment]
Would it be possible to say "uses and contributes to"?  "uses" on this page makes it look like this is all in one direction whereas "contributes" makes it clear this is an active partnership...

**Comment by eduardo-rodrigues** [comment]
That has been up on the website since "always", see https://scikit-hep.org/funding :-). IRIS-HEP is clearly special because it contributes heavily, and also uses some other parts. Would you have a sentence to suggest to what we wrote at https://scikit-hep.org/projusers?

**Comment by eduardo-rodrigues** [comment]
> Would it be possible to say "uses and contributes to"? "uses" on this page makes it look like this is all in one direction whereas "contributes" makes it clear this is an active partnership...

As said, @bbockelm, you make a totally valid and good point. I added a couple of sentences to the page, see https://github.com/scikit-hep/scikit-hep.github.io/pull/93. I will give it a few hours and will then merge unless I hear suggestions for modifications ... Thanks.
